import React, { useState } from 'react';
import TextEditor from '../components/TextEditor';
import { detectAI } from '../lib/api';
import SEO from '../lib/seoHelper';

const AIDetectionPage = () => {
  const [text, setText] = useState('');
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const handleDetectAI = async () => {
    if (!text.trim()) {
      setError('Please enter some text to analyze');
      return;
    }
    
    setLoading(true);
    setError('');
    
    try {
      const data = await detectAI(text);
      setResult(data);
    } catch (err) {
      setError('Failed to analyze text');
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="container mx-auto px-4 py-8">
      <h1 className="text-3xl font-bold mb-6">AI Content Detection</h1>
      
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div>
          <TextEditor 
            value={text} 
            onChange={setText} 
            placeholder="Enter text to analyze for AI-generated content..."
            rows={10}
          />
          <button 
            onClick={handleDetectAI}
            disabled={loading}
            className="mt-4 bg-blue-600 text-white px-6 py-2 rounded-md hover:bg-blue-700 transition-colors disabled:opacity-50"
          >
            {loading ? 'Analyzing...' : 'Detect AI Content'}
          </button>
          {error && <p className="text-red-500 mt-2">{error}</p>}
        </div>
        
        <div>
          {result && (
            <div className="bg-white p-6 rounded-lg shadow-md">
              <h2 className="text-xl font-semibold mb-4">Analysis Results</h2>
              
              <div className="mb-4">
                <h3 className="font-medium text-gray-700 mb-1">AI Probability</h3>
                <div className="w-full bg-gray-200 rounded-full h-4">
                  <div 
                    className="bg-blue-600 h-4 rounded-full" 
                    style={{ width: `${result.aiProbability * 100}%` }}
                  ></div>
                </div>
                <p className="text-sm text-gray-600 mt-1">
                  {Math.round(result.aiProbability * 100)}% likely AI-generated
                </p>
              </div>
              
              <div>
                <h3 className="font-medium text-gray-700 mb-1">Detailed Report</h3>
                <p className="text-gray-800">{result.report}</p>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Content Section for SEO and AdSense */}
      <div className="mt-16 max-w-4xl mx-auto">
        <SEO 
          title="AI Content Detector | Detect ChatGPT & GPT-4 Text | Quetext"
          description="Identify AI-generated content with our advanced detector. High accuracy for ChatGPT, GPT-4, and other LLMs."
        />
        
        <section className="mb-12">
          <h2 className="text-2xl font-bold mb-4">How AI Detection Works</h2>
          <p className="text-gray-700 mb-4">
            Our AI Content Detector uses state-of-the-art machine learning models to analyze the patterns, 
            perplexity, and burstiness of your text. While human writing tends to be varied and 
            unpredictable, AI-generated text often follows specific statistical patterns.
          </p>
          <p className="text-gray-700 mb-4">
            Whether it's ChatGPT, Claude, or Gemini, our tool provides an estimate of how likely the 
            content was generated by an artificial intelligence. This is crucial for maintaining 
            authenticity in journalism, academic integrity in schools, and trust in business communications.
          </p>
        </section>

        <section className="mb-12">
          <h2 className="text-2xl font-bold mb-6">Frequently Asked Questions</h2>
          <div className="space-y-4">
            <div className="border-b pb-4">
              <h3 className="font-semibold text-lg mb-2">Can it detect text from GPT-4 and ChatGPT?</h3>
              <p className="text-gray-600">Yes, our model is trained on a wide variety of datasets, including content generated by the latest models like GPT-4, ChatGPT, and Claude.</p>
            </div>
            <div className="border-b pb-4">
              <h3 className="font-semibold text-lg mb-2">Are the results 100% accurate?</h3>
              <p className="text-gray-600">While our detector is highly accurate, no AI detector is perfect. Results should be used as a guideline. False positives and false negatives can occur, especially with highly edited or technical text.</p>
            </div>
            <div className="border-b pb-4">
              <h3 className="font-semibold text-lg mb-2">Is there a word limit for analysis?</h3>
              <p className="text-gray-600">The free version has a generous word limit per check. For larger documents or high-volume needs, we offer premium plans with increased capacity.</p>
            </div>
            <div className="border-b pb-4">
              <h3 className="font-semibold text-lg mb-2">Why should I use an AI detector?</h3>
              <p className="text-gray-600">AI detection helps ensure that content is human-created, which is important for SEO, academic honesty, and maintaining a personal connection with your audience.</p>
            </div>
          </div>
        </section>
      </div>
    </div>
  );
};

export default AIDetectionPage;