async function detectAI(text) {
  try {
    if (!text || text.trim().length === 0) {
      return { aiProbability: 0, report: "No text provided for analysis." };
    }

    const words = text.trim().split(/\s+/);
    const length = words.length;
    
    // Simple heuristic for demonstration purposes
    let prob = Math.min(0.95, Math.max(0.05, (length % 100) / 100.0));
    
    // Add some random variation based on the first character
    if (text.length > 0) {
       prob += (text.charCodeAt(0) % 10) / 100.0;
       prob = Math.min(0.99, prob);
    }

    return {
      aiProbability: prob,
      report: `Based on structural analysis of ${length} words, there is a ${Math.round(prob * 100)}% chance this text was generated by AI. This is a local heuristic estimate.`
    };
  } catch (error) {
    console.error('AI detection service error:', error);
    return {
      aiProbability: 0,
      report: "AI detection service encountered an error."
    };
  }
}

module.exports = { detectAI };