async function detectAI(text) {
  try {
    if (!text || text.trim().length === 0) {
      return { aiProbability: 0, report: "No text provided for analysis." };
    }

    const words = text.trim().split(/\s+/);
    const length = words.length;
    
    // Robust AI detection heuristic based on structural features
    // AI tends to have more predictable sentence lengths, fewer unique words (lower lexical diversity), 
    // and fewer highly complex punctuation combinations compared to human text.
    
    // Calculate average sentence length
    const sentences = text.split(/[.!?]+/).filter(s => s.trim().length > 0);
    const avgWordsPerSentence = sentences.length > 0 ? length / sentences.length : length;
    
    // Calculate lexical diversity (unique words / total words)
    const uniqueWords = new Set(words.map(w => w.toLowerCase().replace(/[^a-z0-9]/g, ''))).size;
    const lexicalDiversity = uniqueWords / length;
    
    // Base probability starts at 0.5
    let prob = 0.5;
    
    // AI text often has very balanced sentence lengths (around 15-20 words)
    if (avgWordsPerSentence > 12 && avgWordsPerSentence < 22) {
        prob += 0.2;
    } else if (avgWordsPerSentence > 30 || avgWordsPerSentence < 8) {
        prob -= 0.2; // Humans are more likely to write run-on or very short sentences
    }
    
    // AI text often has lower lexical diversity for long texts due to predictable vocabulary
    if (length > 50) {
        if (lexicalDiversity < 0.5) prob += 0.25;
        else if (lexicalDiversity > 0.7) prob -= 0.2;
    }
    
    // Look for common AI transition words ("In conclusion", "Furthermore", "Additionally")
    const aiTransitions = (text.match(/In conclusion|Furthermore|Additionally|Moreover|It is important to note/gi) || []).length;
    prob += (aiTransitions * 0.05);

    // Normalize between 0.01 and 0.99
    prob = Math.max(0.01, Math.min(0.99, prob));
    
    // If text is very short, confidence is low, pull towards 0.5
    if (length < 20) {
        prob = (prob + 0.5) / 2;
    }

    let report = "";
    if (prob > 0.7) {
        report = `Based on structural analysis of ${length} words, there is a ${Math.round(prob * 100)}% chance this text was generated by AI. The text exhibits highly predictable sentence structures, lower lexical diversity, and transition patterns common to Large Language Models.`;
    } else if (prob < 0.4) {
        report = `Based on structural analysis of ${length} words, there is a ${Math.round(prob * 100)}% chance this text was generated by AI. The text shows varied sentence lengths and higher lexical diversity typical of human writing.`;
    } else {
        report = `Based on structural analysis of ${length} words, there is a ${Math.round(prob * 100)}% chance this text was generated by AI. The results are mixed, showing some predictable patterns but also human-like variability.`;
    }

    return {
      aiProbability: prob,
      report: report
    };
  } catch (error) {
    console.error('AI detection service error:', error);
    return {
      aiProbability: 0,
      report: "AI detection service encountered an error."
    };
  }
}

module.exports = { detectAI };